/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ticket.booking;

import org.ticket.booking.entities.Train;
import org.ticket.booking.entities.User;
import org.ticket.booking.services.UserBookingService;
import org.ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.UUID;


public class App {

    public static void main(String[] args) {

        try {

            System.out.println("Running Train Booking System");
            Scanner scanner = new Scanner(System.in);


            int option = 0;
            UserBookingService userBookingService = null;
            Train trainSelectedForBooking = null;
            try {
                userBookingService = new UserBookingService();
            } catch (IOException ex) {
                System.out.println("There is something wrong");
            }
            while (option != 6) {
                System.out.println("Choose option");
                System.out.println("1. Sign up");
                System.out.println("2. Login");
                System.out.println("3. Fetch Bookings");
                System.out.println("4. Search Trains");
                System.out.println("5. Book a Seat");
                System.out.println("6. Exit the App");
                option = scanner.nextInt();
                switch (option) {
                    case 1:
                        System.out.println("Enter the username to signup");
                        String nameToSignUp = scanner.next();
                        System.out.println("Enter the password to signup");
                        String passwordToSignUp = scanner.next();
                        User userToSignup = new User(
                                nameToSignUp,
                                passwordToSignUp,
                                UserServiceUtil.hashPassword(passwordToSignUp),
                                new ArrayList<>(),
                                UUID.randomUUID().toString());


                        Boolean signedUp = userBookingService.signUp(userToSignup);

                        if (signedUp) {
                            System.out.println("Signup Successful");
                        } else {
                            System.out.println("Signup Failed");
                        }
                        break;
                    case 2:
                        System.out.println("Enter the username to Login");
                        String nameToLogin = scanner.next();
                        System.out.println("Enter the password to signup");
                        String passwordToLogin = scanner.next();
                        User userToLogin = new User(
                                nameToLogin,
                                passwordToLogin,
                                null,
                                new ArrayList<>(),
                                null);
                        try {
                            userBookingService = new UserBookingService(userToLogin);

                            Boolean loggedIn = userBookingService.loginUser();

                            if (loggedIn) {
                                System.out.println("Login Successful");
                            } else {
                                System.out.println("Invalid Credentials");
                            }

                        } catch (IOException ex) {
                            ex.printStackTrace();
                        }
                        break;
                    case 3:
                        System.out.println("Fetching your bookings");
                        userBookingService.fetchBooking();
                        break;
                    case 4:
                        System.out.println("Type your source station");
                        String source = scanner.next();

                        System.out.println("Type your destination station");
                        String dest = scanner.next();

                        List<Train> trains = userBookingService.getTrains(source, dest);

                        // Check if no trains found
                        if (trains == null || trains.isEmpty()) {
                            System.out.println("No trains found for given route");
                            break;
                        }

                        int index = 1;

                        // Print trains properly
                        for (Train t : trains) {
                            System.out.println(index + ". Train id : " + t.getTrainId());

                            for (Map.Entry<String, String> entry : t.getStationTimes().entrySet()) {
                                System.out.println("Station: " + entry.getKey() + " | Time: " + entry.getValue());
                            }

                            System.out.println("----------------------------------");
                            index++;
                        }

                        System.out.println("Select a train by typing 1,2,3...");

                        int choice = scanner.nextInt();

                        // Validate selection
                        if (choice <= 0 || choice > trains.size()) {
                            System.out.println("Invalid selection");
                            break;
                        }

                        trainSelectedForBooking = trains.get(choice - 1);

                        System.out.println("You selected: " + trainSelectedForBooking.getTrainId());

                        break;
                    case 5:
                        if (trainSelectedForBooking == null) {
                            System.out.println("Please search and select a train first");
                            break;
                        }

                        System.out.println("Select a seat out of these seats");
                        List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                        for (List<Integer> row : seats) {
                            for (Integer val : row) {
                                System.out.print(val + " ");
                            }
                            System.out.println();
                        }
                        System.out.println("Select the seat by typing the row and column");
                        System.out.println("Enter the row (1 to 4):");
                        int row = scanner.nextInt()-1;
                        System.out.println("Enter the column (1 to 6):");
                        int col = scanner.nextInt()-1;
                        System.out.println("Booking your seat....");
                        Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, col);
                        if (booked.equals(Boolean.TRUE)) {
                            System.out.println("Booked! Enjoy your journey");
                        } else {
                            System.out.println("Can't book this seat");
                        }
                        break;
                    default:
                        break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
